apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}
  labels:
    app: workshop
spec:
  maxReplicas: {{ .Values.limits.max }}
  minReplicas: {{ .Values.limits.min }}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: myhpa
  targetCPUUtilizationPercentage: 85
